language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=helics
script:
  - brew tap GMLC-TDC/helics
  - brew install -v $PACKAGE

branches:
  except:
    - gh-pages

notifications:
  email: false
