language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/GMLC-TDC
  - ln -s $PWD $(brew --repo)/Library/Taps/GMLC-TDC/homebrew-helics
  - brew tap --repair
env:
  - PACKAGE=helics
script:
  - brew tap GMLC-TDC/helics
  - brew install -v $PACKAGE --HEAD

branches:
  except:
    - gh-pages

notifications:
  email: false
