language: objective-c
osx_image: xcode10.2
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps/GMLC-TDC
  - ln -s $PWD $(brew --repo)/Library/Taps/GMLC-TDC/homebrew-helics
  - brew tap --repair
  
env:
  global:
    - PACKAGE=helics

jobs:
  include:
    - env: VERSION="--HEAD"
    # Make sure the stable version builds for formula updates getting merged to master
    - if: branch = master
      env: VERSION=""
      
script:
  - brew tap GMLC-TDC/helics
  - brew install -v $PACKAGE $VERSION

branches:
  except:
    - gh-pages

notifications:
  email: false
